# Generated by Django 4.2 on 2024-06-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='computer_name',
        ),
        migrations.RemoveField(
            model_name='usersinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usersinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usersinfo',
            name='number',
        ),
    ]
