# Generated by Django 4.2 on 2024-06-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_computers_computer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='computer_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
