# Generated by Django 4.2 on 2024-06-04 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_reservations_user_id_delete_usersinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_time',
        ),
        migrations.AddField(
            model_name='reservations',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
